- .babelrc
- package.json
- yarn.lock
babel-preset-es2016 is not including the features we use.
Please check them:
* https://github.com/babel/babel/tree/master/packages/babel-preset-es2016
* https://github.com/babel/babel/tree/master/packages/babel-preset-es2015
Also, we should always update/manage our deps via yarn and keep the yarn.lock updated.
This is also fixing the failing build of the develop branch:
* https://travis-ci.org/netceteragroup/girders-elements/builds/184603428
> Set babel-preset-es2015 instead es2016, update yarn file and fix build

- src/engine/engine.js
Unsubscribe from redux store before the engine component unmounts.
> Unsubscribe from redux store

- package.json
- packages/core/src/__tests__/ui.js
- packages/core/src/common/__tests__/element.js
- packages/core/src/common/element.js
- packages/core/src/ui/uiRegistry.js
- yarn.lock
The element's UI component is passed down a uiFor fn which is used to 'navigate down' the structure of the elements.
Example:
```javascript
// instead of 
import ui from '@girders-elements/core';
ui.register('dummy', ({element}) => {
return (
<div>{ui.forElement(element.get('child'))}</div>
);
});
// use 
ui.register('dummy', ({element, uiFor}) => {
return (
<div>
{uiFor('child')}
<p>Also works with lists</p>
{uiFor('items')} 
</div>
);
});
```
> feat(core): A new`uiFor` prop (passed down to elements).

- packages/core/src/__tests__/ui.js
- packages/core/src/impl/deprecated.js
- packages/core/src/impl/warning.js
- packages/core/src/ui/uiRegistry.js
The `ui.forElement`and `ui.forElements` functions are deprecated and will be removed in a future release. Please use `uiFor` function provided as a property to your element ui implementation.
Each element in the UI tree must refer to an *unchanged* element in the state tree. Allowing arbitrary calls to `forElement(s)` allows the users to transform elements in an e.g. parent node before passing them down to child nodes, so they are deprecated.
Imposing this restriction allows us to optimize the re-rendering calls to just the sub-tree where the change had happened. This is an important optimization as a top-level elements often use 3rd party heavy components (e.g. react-navigation) which aren't optimized for frequent re-rendering like ordinary element UI is.
> feat(core): deprecate ui.forElement and ui.forElements

- README.md
- packages/core/src/__tests__/read.js
- packages/core/src/read/elements/loading.js
- packages/core/src/read/elements/read.js
- packages/core/src/read/reducer.js
BREAKING: This pull request contains a breaking change for the reads functionality.
* When performing a read, the JSON response overrides the sub-state that initiated the read operation 
* Get rid of the 'where' property of the reads
* Get rid of the 'where' prop of the Loading and Read components
> Simplify reads

- packages/components/src/viewport/aware/index.js
This pull request contains the following enhancements:
- Optimisation of the layout measurements done for viewport aware components
- Fix of a bug where the state of the component would be set even after it has been unmounted (React triggers a warning because of this)
> Improve viewport awareness higher-order component

- packages/core/src/impl/log.js
- packages/core/src/read/impl.js
Currently, when `actions.readRefresh()` is dispatched and results with a failure, an error is logged to the console, which triggers React Native's red screen:
The red screen is not needed since this is not an invalid state. We only need to dispatch an action that will set `refreshing` to `false`.
> avoid logging an error during readRefresh

- packages/core/src/ui/index.js
This will print a proper warning inside the console to warn about missing kinds inside the registry.
Specially if the code base is huge a developer can easily see if the registry is missing some types.
> Add warning for unregistered kinds

- packages/core/src/read/__tests__/read.js
- packages/core/src/read/actions.js
- packages/core/src/read/impl.js
- packages/core/src/read/index.js
When a `readRefresh` fails, trace  (the failed read metadata) is left in the element's [propNames.metadata].failedRefresh
> Add `failedRefresh` to the  metadata of a refreshed element.

- packages/core/src/read/__tests__/http.js
- packages/core/src/read/http.js
- packages/core/src/read/impl.js
420 seems to be used by react-native XHR to report network connectivity problems.
Use 999 to differentiate programming errors from other http progems.
> replace code 420 with 999 for exceptions

- packages/components/src/viewport/aware/index.js
- packages/components/src/viewport/tracker/__tests__/tracker.js
- packages/components/src/viewport/tracker/index.js
This PR will fix multiple bugs that used to occur because the changes in the size of the tracked component's content (the one wrapped with `Viewport.Tracker`) were ignored.
> Always remeasure layout on content size change

- packages/components/src/shared/WithEvents.js
- packages/components/src/viewport/aware/index.js
- packages/components/src/viewport/tracker/__tests__/tracker.js
- packages/components/src/viewport/tracker/index.js
This PR will:
- Include notification of listeners upon listener add in `WithEvents.js`
- Make sure `ViewportTracker` does not notify listeners with incomplete event data
- Enable `ViewportAware` to reattempt layout measurement in case one was requested while the component has not yet been mounted
> Notify listeners on add

- .travis.yml
- packages/core/src/read/__tests__/http.js
- packages/core/src/read/__tests__/read.js
- packages/core/src/read/impl.js
- packages/core/src/read/index.js
This pull request exposes a `perform` method in the read system that allows you to fetch (read) content using the system's current configuration (registered readers, transformers, etc.)
The API is is with a similar signature of a reader:
```javascript
perform :: (uri, opts) => Promise<ReadResponse>
```
The method is available in the running system's read subsystem:
```javascript
const kernel = Kernel.create(...)
const val = await kernel.subsystems.read.perform(uri)
```
Consequently, the method is available via the context  param to effects, etc.
> feat(core): read.perform()

- packages/core/src/data/index.js
- packages/core/src/zip/__tests__/reduce.js
- packages/core/src/zip/index.js
- packages/core/src/zip/reduce.js
Adds the following methods in `zip` (they are curried):
```javascript
declare function reduce<T>(
fn: (acc: T, item: any) => T,
initialAcc: T,
zipper: Zipper
): T
```
```javascript
declare function reducePre<T>(
fn: (acc: T, item: any) => T,
initialAcc: T,
zipper: Zipper
): T
```
These functions preform a reduction of the zipper tree in post (`reduce`) or pre (`reducePre`) order.
Also, the following method is added in `data`:
```javascript
declare function when<T>(
pred: (item: any) => Boolean),
fn: (acc: T, item: any) => T
): (acc: T, item:any) => T
```
It helps writing zip reducing using a predicate.
Closes https://github.com/netceteragroup/girders-elements/issues/82
> feat(core): Implement reduce for zippers

- packages/core/src/__tests__/read.js
- packages/core/src/core/index.js
- packages/core/src/enhance/__tests__/enhance.js
- packages/core/src/enhance/impl.js
- packages/core/src/enhance/index.js
- packages/core/src/index.js
- packages/core/src/read/__tests__/read.js
- packages/core/src/read/impl.js
- packages/core/src/read/index.js
Implement *enhancers* as an alternative to *enrichers*.
Profiling showed that there is a significant performance impact of using enrichers mostly due to the inefficient Promise implementation present in react native. Enhancers are a solution (probably a temporary one) that should perform better.
Enhancers, like enrichers are registered for a specific element, but they will be only allowed to act on root level elements.
Enhancers have the API
```javascript
// registration
enhance.register(kind, enhancer)
// enhancer signature
enhancer :: async (el, context) => (el => el)
```
In other words, they take the element, an optional context and then return an updating fn that will eventually apply the enhancement to the element in question.
All enhancers are run in parallel on the read document. …
> Enhancers (an alternative to Enrichers)

- packages/core/src/zip/__tests__/edit.js
- packages/core/src/zip/edit.js
- packages/core/src/zip/index.js
Utility function that mimics the behavior of transformers: a way to walk the element tree and perform edits for given patterns.
The function has the signature:
```javascript
editCond :: patterns -> loc -> loc
```
Where patterns is an array of `[pattern, editFn]` touples.
A pattern can be either a function, in which case it is treated as a predicate; alternatively it can be an element kind expression, in which case it will match all elements of that kind.
e.g.
```javascript
zip.editCond(
[
[e => e.has('property'), e => e.set('updated', true),
['__read',  e => e.set('isRead', true),
[['document', 'article'], e => e.set('isDocumentArticle', true)
],
initialLocation
)
```
Closes #81
> Implement zip.editCond

- packages/core/src/enhance/impl.js
This commit will fix the resolution process by providing a standard JS array to `Promise.all` instead of an immutable one.
> Fix resolution of registered enhancers to updates

- packages/core/src/enhance/__tests__/enhance.js
- packages/core/src/enhance/impl.js
- packages/core/src/enhance/index.js
- packages/core/src/enrich/impl.js
- packages/core/src/impl/util.js
- packages/core/src/read/impl.js
- packages/core/src/read/index.js
- packages/core/src/registry/AbstractRegistry.js
- packages/core/src/registry/PatternRegistry.js
- packages/core/src/registry/Registry.js
- packages/core/src/registry/RegistryChain.js
Add support for allowing **_editCond-style_ patterns** as a return value for enhancers. With this, we will run those updates in an optimized way.
Add support for **read-independent enhancers**. These enhancers are not connected with a certain kind, but are executed in parallel with the read.
With the above changes, the enhance API now is the following:
```javascript
// registration (read-dependent)
enhance.register(kind, enhancer)
// enhancer signature (read-dependent)
enhancer :: async (el, context) => (el => el) || [[pattern, el => el], ...]
// registration (read-independent)
enhance.register(enhancer)
// enhancer signature (read-independent)
enhancer :: async context => (el => el) || [[pattern, el => el], ...]
```
Bonus: enrichers tree-walk is not done when there are no registered …
> Enhance Improvements: pattern-based results as options and read-independent enhancers support

- packages/components/README.md
- packages/components/src/index.js
- packages/components/src/viewport/aware/index.js
- packages/components/src/viewport/withPlaceHolder/index.web.js
- packages/components/src/viewport/withPlaceholder/index.js
- packages/components/src/viewport/withPlaceholder/index.web.js
- Added `onViewportEnter` and `onViewportLeave` callbacks to `Viewport.Aware`
- Used the chance to refactor `WithPlaceHolder` to `WithPlaceholder`, since "placeholder" is a single word
- Extended the Skele Components documentation
> Add viewport enter and leave callbacks

- packages/components/README.md
- packages/components/src/viewport/withPlaceholder/index.js
This feature is inspired by a [Medium comment](https://medium.com/@dvoskanyan2/thanks-for-a-documentation-33edc09cad0c).
It adds support for keeping a component wrapped by `Viewport.WithPlaceholder` displayed once it enters the viewport.
With `retainOnceInViewport` set to `false` (default behavior), the component will be replaced by a placeholder once it leaves the viewport.
With `retainOnceInViewport` set to `true`, the component will be kept displayed.
> feat(components): Add retainOnceInViewport prop to Viewport.WithPlaceholder

- packages/components/README.md
- packages/components/src/viewport/aware/index.js
A bug [reported via Medium](https://medium.com/@sagarguhe/hi-blagoja-evkoski-thanks-for-such-a-great-component-this-works-like-a-charm-e5959aa64056).
The reporter [worked around the issue](https://medium.com/@sagarguhe/ok-so-wrapping-a-video-inside-viewport-aware-view-solved-the-issue-238374685e77).
This PR addresses the problem.
> fix(components): Allow access to the inner reference of viewport-aware components

- packages/core/src/data/__tests__/element-benchmarks.js
- packages/core/src/data/__tests__/element.js
- packages/core/src/data/element.js
- packages/core/src/registry/Registry.js
- packages/core/src/registry/__tests__/Registry.js
Resolves #120.
Initial benchmarks:
```
canonical non-memoized x 116,203 ops/sec ±8.39% (69 runs sampled)
isOfKind non-memoized x 61,168 ops/sec ±0.26% (95 runs sampled)
canonical memoized x 512,298 ops/sec ±8.66% (71 runs sampled)
isOfKind memoized x 69,476 ops/sec ±0.56% (86 runs sampled)
```
Check https://github.com/netceteragroup/skele/pull/124#issuecomment-445448152 for updated benchmarks.
> feat(core): memoize the normalize function

- packages/core/src/index.js
- packages/core/src/zip/elementZipper.js
- packages/core/src/zip/skele/__tests__/zipperImpl.js
- packages/core/src/zip/skele/index.js
- packages/core/src/zip/skele/zipperImpl.js
A simplified zipper over the Skele tree structure. It is meant to replace
`elementZipper` which is now deprecated.
`skeleZip` does not take any configuration and **requires** explicite annotation of children  properties (using `@@skele/children`) in the tree.
To use it:
```javascript
import { skeleZip } from '@skele/core'
const rootLoc = skeleZip(state)
```
> feat(core): skeleZip

- packages/core/src/zip/__tests__/edit.js
- packages/core/src/zip/edit.js
There is a bug in the implementation of editCond. Performance optimization introduced, have made usage of "patterns" for kinds to be stored in a Registry, making the usage to only return one transformation per kind.
By moving to MultivalueRegistry, we again are doing all registered transformations.
> Make editCond to work with all kinds (specific or abstract)

- packages/components/src/viewport/aware/index.js
- packages/components/src/viewport/tracker/__tests__/tracker.js
- packages/components/src/viewport/tracker/index.js
Solves https://github.com/netceteragroup/skele/issues/114
> feat(components): Extend viewport awareness for horizontally scrollable views
